http://localhost:3000/banner

####
POST http://localhost:3000/categoria HTTP/1.1
content-type: application/json

{
    "nome": "Esporte"
}

####

PUT http://localhost:3000/banner/3 HTTP/1.1
content-type: application/json

{
    "titulo": "Alunos 33",
      "imagem": "https://www.moblee.com.br/blog/wp-content/uploads/sites/2/2018/03/Organizando-eventos-as-principais-etapas-de-um-projeto-e-o-que-fazer-em-cada-uma-1.png",
      "link": "http://unesc.net/portal/"
}
####

DELETE http://localhost:3000/banner/2 HTTP/1.1
content-type: application/json

####

GET http://localhost:3000/bannercategId=1 HTTP/1.1
content-type: application/json

#####

GET http://localhost:3000/banner?_sort=dataInicial&_order=desc&titulo_like= HTTP/1.1
content-type: application/json

#####

